# This is a basic workflow to help you get started with Actions

name: Monthly Scraper

# Controls when the workflow will run
on:
  schedule:
    # 07.00 GMT+7
    - cron: 0 0 1 * *
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Scrape
        uses: docker://mcr.microsoft.com/playwright:v1.14.0-focal
        with:
          args: make action
          
