
name: Monthly Scraper

on:
  schedule:
    # 07.00 GMT+7
    - cron: 0 0 1 * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Scrape
        uses: docker://mcr.microsoft.com/playwright:v1.14.0-focal
        with:
          args: make action
          
